# Generated by Django 3.0.7 on 2020-06-13 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchProfile',
            fields=[
                ('name_twitch', models.TextField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField(unique=True)),
                ('oidc_token', models.TextField(default=None, max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Twitch профиль',
                'verbose_name_plural': 'Twitch профили',
            },
        ),
        migrations.CreateModel(
            name='VKProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_tokken', models.TextField(max_length=128, unique=True)),
                ('vk_page_URL', models.URLField(unique=True)),
                ('vk_key_group', models.TextField(max_length=21)),
            ],
            options={
                'verbose_name': 'VK профиль',
                'verbose_name_plural': 'VK профили',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='tg_auth_key',
            field=models.TextField(default=models.IntegerField(unique=True, verbose_name='ID чата Telegram'), max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tg_chat_id',
            field=models.IntegerField(unique=True, verbose_name='ID чата Telegram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitch_profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.TwitchProfile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vk_profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.VKProfile'),
        ),
    ]
