# Generated by Django 3.0.7 on 2020-06-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200613_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='tg_auth_key',
            field=models.TextField(default=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID чата Telegram'), max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tg_chat_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID чата Telegram'),
        ),
    ]
