# Generated by Django 3.0.7 on 2020-06-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200613_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tg_auth_key',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitch_profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vk_profile',
        ),
        migrations.DeleteModel(
            name='TwitchProfile',
        ),
        migrations.DeleteModel(
            name='VKProfile',
        ),
    ]
