# Generated by Django 3.0.7 on 2020-06-13 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200613_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twitchprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='twitchprofile',
            name='oidc_token',
        ),
        migrations.AlterField(
            model_name='twitchprofile',
            name='name_twitch',
            field=models.TextField(blank=True, max_length=15, unique=True, verbose_name='Имя пользователя'),
        ),
        migrations.CreateModel(
            name='TwitchStreamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oidc_token', models.TextField(blank=True, default=None, max_length=128, unique=True)),
                ('sub_list', models.ManyToManyField(to='website.TwitchProfile')),
                ('twitch_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Профиль twitch+', to='website.TwitchProfile')),
            ],
        ),
    ]
