# Generated by Django 3.0.7 on 2020-06-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200613_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twitchprofile',
            options={'verbose_name': 'Профиль twitch'},
        ),
    ]
