# Generated by Django 3.0.7 on 2020-06-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200613_2159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.RemoveField(
            model_name='twitchstreamer',
            name='sub_list',
        ),
        migrations.RemoveField(
            model_name='twitchstreamer',
            name='twitch_profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='TwitchProfile',
        ),
        migrations.DeleteModel(
            name='TwitchStreamer',
        ),
    ]
