# Generated by Django 3.0.7 on 2020-06-14 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0011_auto_20200614_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('chat_id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID чата с ботом')),
                ('username', models.TextField(verbose_name='Имя пользователя')),
                ('name', models.TextField(verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Профиль Telegram',
                'verbose_name_plural': 'Профили Telegram',
            },
        ),
        migrations.CreateModel(
            name='TwitchProfile',
            fields=[
                ('username', models.TextField(max_length=15, primary_key=True, serialize=False, verbose_name='Имя пользователя')),
                ('url', models.URLField(verbose_name='Ссылка на профиль Twitch')),
                ('oidc_token', models.TextField(blank=True, unique=True, verbose_name='OIDC токен')),
            ],
            options={
                'verbose_name': 'Профиль Twitch',
                'verbose_name_plural': 'Профили Twitch',
            },
        ),
        migrations.CreateModel(
            name='VKGroup',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='ID Группы')),
                ('name', models.TextField(verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа VK',
                'verbose_name_plural': 'Группы VK',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('twitch_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.TwitchProfile', verbose_name='Twitch профиль')),
                ('time_end_of_subs', models.DateTimeField(verbose_name='Конец подписки')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='VKProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('vk_token', models.TextField(blank=True, verbose_name='Токкен доступа')),
                ('url', models.URLField(verbose_name='URL ссылка на профиль')),
                ('vk_groups', models.ManyToManyField(blank=True, to='website.VKGroup', verbose_name='Группы VK')),
            ],
            options={
                'verbose_name': 'Профиль VK',
                'verbose_name_plural': 'Профили VK',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_profile', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.TelegramProfile', verbose_name='Профиль Telegram')),
                ('twitch_profile', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.TwitchProfile', verbose_name='Профиль Twitch')),
                ('vk_profile', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.VKProfile', verbose_name='Профиль VK')),
                ('subscribe_list', models.ManyToManyField(to='website.Subscribe', verbose_name='Список подписок')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
