# Generated by Django 3.0.7 on 2020-06-15 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_profile_subscribe_telegramprofile_twitchprofile_vkgroup_vkprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribe_list',
            field=models.ManyToManyField(blank=True, related_name='Подписки', to='website.Subscribe', verbose_name='Список подписок'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitch_profile',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Профиль Twitch+', to='website.TwitchProfile', verbose_name='Профиль Twitch'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='twitch_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.TwitchProfile', verbose_name='Twitch профиль'),
        ),
    ]
