# Generated by Django 3.0.7 on 2020-06-15 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20200615_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='twitch_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.TwitchProfile', verbose_name='Twitch профиль'),
        ),
        migrations.AlterField(
            model_name='twitchprofile',
            name='url',
            field=models.URLField(default='https://twitch.tv/<django.db.models.fields.TextField>', verbose_name='Ссылка на профиль Twitch'),
        ),
        migrations.AlterField(
            model_name='twitchprofile',
            name='username',
            field=models.TextField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
