# Generated by Django 3.0.7 on 2020-06-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200615_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='twitch_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Профиль Twitch+', to='website.TwitchProfile', verbose_name='Профиль Twitch'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.VKProfile', verbose_name='Профиль VK'),
        ),
    ]
