# Generated by Django 3.0.7 on 2020-06-15 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20200615_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscribe_list',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='sub_list',
            field=models.ManyToManyField(related_name='Подписчики', to='website.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitch_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.TwitchProfile', verbose_name='Профиль Twitch'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='time_end_of_subs',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец подписки'),
        ),
    ]
