# Generated by Django 3.0.7 on 2020-06-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20200615_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='sub_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='Подписчики', to='website.Profile'),
        ),
    ]
