# Generated by Django 3.0.7 on 2020-06-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20200615_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='chat_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID чата с ботом'),
        ),
    ]
