# Generated by Django 3.0.7 on 2020-06-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20200615_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='sub_list',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='twitch_profile',
        ),
        migrations.RemoveField(
            model_name='vkprofile',
            name='vk_groups',
        ),
        migrations.RemoveField(
            model_name='twitchprofile',
            name='oidc_token',
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='subscription_list',
            field=models.ManyToManyField(blank=True, related_name='Подписки', to='website.TwitchProfile'),
        ),
        migrations.AddField(
            model_name='twitchprofile',
            name='follower_list',
            field=models.ManyToManyField(blank=True, related_name='Подписчики', to='website.TelegramProfile'),
        ),
        migrations.AddField(
            model_name='twitchprofile',
            name='message',
            field=models.TextField(blank=True, default='Пользователь <django.db.models.fields.TextField> начал прямую трансляцию.\n Заходи <django.db.models.fields.URLField>', max_length=140, verbose_name='Текст уведомления'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='VKGroup',
        ),
        migrations.DeleteModel(
            name='VKProfile',
        ),
    ]
