# Generated by Django 3.0.7 on 2020-06-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20200615_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitchprofile',
            name='follower_list',
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='subscription_list',
            field=models.ManyToManyField(blank=True, related_name='Подписки', to='website.TwitchProfile', verbose_name='Подписки'),
        ),
    ]
