# Generated by Django 3.0.7 on 2020-06-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20200615_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramprofile',
            old_name='subscription_list',
            new_name='subscriptions',
        ),
    ]
