# Generated by Django 3.0.7 on 2020-06-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20200615_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='website.TwitchProfile', verbose_name='Подписки'),
        ),
    ]
