# Generated by Django 3.0.7 on 2020-06-15 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20200615_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='VKGroup',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='ID Группы')),
                ('name', models.TextField(verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа VK',
                'verbose_name_plural': 'Группы VK',
            },
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='subscriptions',
        ),
        migrations.CreateModel(
            name='VKProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('vk_token', models.TextField(blank=True, verbose_name='Токкен доступа')),
                ('url', models.URLField(verbose_name='URL ссылка на профиль')),
                ('vk_groups', models.ManyToManyField(blank=True, to='website.VKGroup', verbose_name='Группы VK')),
            ],
            options={
                'verbose_name': 'Профиль VK',
                'verbose_name_plural': 'Профили VK',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='subscriptions', to='website.TwitchProfile', verbose_name='Подписки')),
                ('tg_profile', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.TelegramProfile', verbose_name='Профиль Telegram')),
                ('twitch_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.TwitchProfile', verbose_name='Профиль Twitch')),
                ('vk_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.VKProfile', verbose_name='Профиль VK')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
