# Generated by Django 3.0.7 on 2020-06-15 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20200615_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vkprofile',
            old_name='vk_groups',
            new_name='groups',
        ),
        migrations.RenameField(
            model_name='vkprofile',
            old_name='vk_token',
            new_name='token',
        ),
        migrations.AddField(
            model_name='twitchprofile',
            name='oidc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tg_profile',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tg', to='website.TelegramProfile', verbose_name='Профиль Telegram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitch_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tw', to='website.TwitchProfile', verbose_name='Профиль Twitch'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vk', to='website.VKProfile', verbose_name='Профиль VK'),
        ),
    ]
